# -> docker compose up
# -> make test-integration
services:
  postgres:
    image: postgres:17
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: testadmin
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    tmpfs:
      - /var/lib/postgresql/data
