apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-postgresdatabase-admin-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - postgres.crds.lunarys.lab
  resources:
  - postgresdatabases
  verbs:
  - '*'
- apiGroups:
  - postgres.crds.lunarys.lab
  resources:
  - postgresdatabases/status
  verbs:
  - get