apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-postgresdatabase-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - postgres.crds.lunarys.lab
  resources:
  - postgresdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.crds.lunarys.lab
  resources:
  - postgresdatabases/status
  verbs:
  - get